import AboutPageNavIcon from '../ui/svg/AboutPageNavIcon';
import BlogPageNavIcon from '../ui/svg/BlogPageNavIcon';
import CatalogPageNavIcon from '../ui/svg/CatalogPageNavIcon';
import ContactPageNavIcon from '../ui/svg/ContactPageNavIcon';
import EmailIcon from '../ui/svg/EmailIcon';
import FacebookIcon from '../ui/svg/FacebookIcon';
import HomePageNavIcon from '../ui/svg/HomePageNavIcon';
import InstagramIcon from '../ui/svg/InstagramIcon';
import LocationIcon from '../ui/svg/LocationIcon';
import PhoneIcon from '../ui/svg/PhoneIcon';
import Tg from '../ui/svg/Tg';
import Viber from '../ui/svg/Viber';
import WhatsApp from '../ui/svg/WhatsApp';

export const menuIcons = [
	<HomePageNavIcon key={'0'} />,
	<CatalogPageNavIcon key={'1'} />,
	<AboutPageNavIcon size={30} key={'2'} />,
	<BlogPageNavIcon key={'3'} />,
	<ContactPageNavIcon key={'4'} />,
];

export const iconData = contacts => [
	{
		icon: <LocationIcon />,
		text: contacts.address,
		href: contacts.addressUrl,
	},
	{
		icon: <PhoneIcon />,
		text: `+${contacts.phone}`,
		href: `tel:+${contacts.phone}`,
	},
	{
		icon: <EmailIcon />,
		text: contacts.email,
		href: `mailto:${contacts.email}`,
	},
];

export const socialLinks = (watsapp, viber, tg, fb, insta) => [
	{ link: watsapp, icon: <WhatsApp />, label: 'whatsapp' },
	{ link: viber, icon: <Viber />, label: 'viber' },
	{ link: tg, icon: <Tg />, label: 'telegram' },
	{ link: fb, icon: <FacebookIcon />, label: 'facebook' },
	{ link: insta, icon: <InstagramIcon />, label: 'instagram' },
];

export const metaKeywords = [
	'israel',
	'Israel',
	'лестницы',
	'stairs',
	'סולמות',
	'деревянные изделия',
	'solid wood panels',
	'wooden products',
	'מוצרים מעץ',
	'щиты из цельного дерева',
	'לוחות עץ',
	'полки',
	'shelves',
	'מדפים',
	'столешницы',
	'countertops',
	'דודים',
	'деревянные полы',
	'wooden floors',
	'רצפות עץ',
	'дуб',
	'oak',
	'אלון',
	'Фанера',
	'Plywood',
	'פליט',
	'МДФ',
	'MDF',
	'Medium Density Fiberboard',
	'Фанерно-деревянная плита средней плотности',
	'Фанерные двери',
	'Plywood doors',
	'דלתות מפליט',
	'Деревянные балки',
	'Wooden beams',
	'קרורות עץ',
	'Деревянные окна',
	'Wooden windows',
	'חלונות עץ',
	'Мебель из дуба',
	'Oak furniture',
	'רהיטים מאלון',
	'Деревянные рамы',
	'Wooden frames',
	'מסגרות עץ',
	'Деревянные перила',
	'Wooden railings',
	'סולמות עץ',
	'Деревянные детали',
	'Wooden details',
	'פרטי עץ',
	'Фанерные стены',
	'Plywood walls',
	'קירות מפליט',
	'Дубовые двери',
	'Oak doors',
	'דלתות אלון',
	'Дубовые полы',
	'Oak floors',
	'רצפות אלון',
	'Дубовая мебель',
	'Oak furniture',
	'רהיטים מאלון',
	'Дубовые бруски',
	'Oak beams',
	'בלוקי אלון',
	'Дубовые лестницы',
	'Oak staircases',
	'סולמות אלון',
	'Ashkelon',
	'אַשְׁקְלוֹן',
	'Ашкелон',
	'Ashdod',
	'אַשְׁדוֹד',
	'Ашдод',
	'Be’er Sheva',
	'בְּאֵר שֶׁבַע',
	'Беэр-Шева',
	'Kiryat Gat',
	'קִרְיַת גַּת',
	'Кирьят Гат',
	'Netivot',
	'נְתִיבוֹת',
	'Нетивот',
	'Ofakim',
	'אוֹפָקִים',
	'Офаким',
	'Jerusalem',
	'יְרוּשָׁלַיִם',
	'Иерусалим',
	'Tel Aviv',
	'תֵּל אָבִיב',
	'Тель-Авив',
	'Haifa',
	'חֵיפָה',
	'Хайфа',
	'Rishon LeZion',
	'רִאשׁוֹן לְצִיוֹן',
	'Ришон-ле-Цион',
	'Petah Tikva',
	'פֶּתַח תִּקְוָה',
	'Петах-Тиква',
	'Netanya',
	'נְתַנְיָה',
	'Нетания',
	'Herzliya',
	'הֶרְצְלִיָּה',
	'Герцелия',
	'Holon',
	'חוֹלוֹן',
	'Холон',
	'Eilat',
	'אֵילַת',
	'Эйлат',
	'Beer Sheva',
	'בְּאֵר שֶׁבַע',
	'Беэр-Шева',
	'Kfar Saba',
	'כְּפַר סַבָּא',
	'Кфар Саба',
	'Rehovot',
	'רְחוֹבוֹת',
	'Реховот',
	'Hod HaSharon',
	'הוֹד הַשָׁרוֹן',
	'Ход Ха-Шарон',
	'Modiin',
	'מוֹדִיעִין',
	'Модиин',
	'Sderot',
	'שדרות',
	'ישראל',
];
